feat: add newsletter form
mihaildanilov/TheRaccoons pull request #65
Opened 2024-05-10 15:07 UTC by mihaildanilov

2024-05-12 13:10 UTC, oakw requested changes
Great, just some minor things. You may also fix that `.env` comment in a separate PR.

2024-05-12 13:10 UTC, oakw commented on frontend/messages/lv.json
> +  "Newsletter": {
```  "Newsletter": {
    "header": "Piesakies jaunumiem!",
    "description": "Abonē, lai uzzinātu par gaidāmajiem hakatoniem, darbnīcām un daudz ko citu!",
    "placeholderTitle": "E-pasts",
    "additionalInfo": "*aizpildot šo veidlapu, tu piekrīti saņemt mūsu e-pasta ziņojumus. Jebkurā laikā vari anulēt savu abonementu.",
    "errorMessage": "Lūdzu, ievadi derīgu e-pasta adresi.",
    "buttonText": "Abonēt",
    "listUUID": "f0ac2134-a0e1-4de0-b43f-f56f531102d0"
    

When creating new texts further, stick to the singular form ('tu'/'tev'/'tavs')

2024-05-12 22:12 UTC, mihaildanilov commented
Done, all changes have been applied as requested.

2024-05-13 19:39 UTC, oakw requested changes
![Screenshot_20240513-212948](https://github.com/mihaildanilov/TheRaccoons/assets/80841359/302c0f44-2793-45d5-a3cf-58378d364e49)

The padding seems to be missing, especially on smaller screens

2024-05-14 15:03 UTC, oakw approved these changes

2024-05-15 13:05 UTC, merged